version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: sabor_rota_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - sabor_rota_postgres_data:/var/lib/postgresql/data
    networks:
      - sabor_rota_network
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sabor_rota_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - sabor_rota_pgadmin_data:/var/lib/pgadmin
    networks:
      - sabor_rota_network
    ports:
      - "8081:80"
    depends_on:
      - db

networks:
  sabor_rota_network:
    driver: bridge

volumes:
  sabor_rota_postgres_data:
    driver: local
  sabor_rota_pgadmin_data:
    driver: local
